---
name: linode-cli
version: "5.59.0"
summary: "Linode CLI"
description: |
  Manage your Akamai Cloud account from your terminal.
  Invoke with `linode-cli`, `linode`, or `lin`.

grade: stable
confinement: strict
base: core24

icon: icon.png

parts:
  linode-cli:
    plugin: python
    source: .
    python-packages:
      - linode-cli==$SNAPCRAFT_PROJECT_VERSION

apps:
  linode-cli:
    command: bin/linode-cli
    plugs:
      - home
      - network
    aliases:
      - linode
      - lin
