---
name: linode-cli
title: Linode CLI
base: core24
version: "5.59.0"
summary: "Control your Akamai Cloud account from your terminal."
description: |
  The Linode CLI puts the power of Akamai Cloud at your fingertips.
  Provision, configure, and tear down Linode instances, manage
  block and object storage, deploy Kubernetes clusters, configure Cloud
  Firewalls, administer DNS records, and more without ever leaving the shell.

  Invoke with `linode-cli`, `linode`, or simply `lin`.

grade: stable
confinement: strict

icon: icon.png

parts:
  linode-cli:
    plugin: python
    source: .
    python-packages:
      - linode-cli==$SNAPCRAFT_PROJECT_VERSION

apps:
  linode-cli:
    command: bin/linode-cli
    aliases:
      - linode
      - lin
    plugs:
      - home
      - network
