---
name: linode-cli
title: Linode CLI
version: "5.61.0"
license: MIT
summary: "An easy way to interact with Akamai Cloud through a command-line interface."
description: |
  The [Linode CLI](https://github.com/linode/linode-cli) is a wrapper around the [Linode API](https://techdocs.akamai.com/linode-api/reference/api), which gives you the ability to manage your [Akamai Cloud](https://www.linode.com) account from the command line. Almost any task that can be done through Cloud Manager can also be performed through the CLI.

  ## Features
  - **Accelerate common tasks.** Running common tasks is trivial with the CLI. Create Linodes and NodeBalancers, and attach block or object storage volumes without leaving your terminal.
  - **Customizable output.** The CLI prints easily readable output by default. You can also specify which fields are returned by the CLI and request JSON responses.
  - **Easy scripting.** Everything you can do with the Cloud Manager can be done through the CLI. The CLI has an easy-to-use interface that makes it perfect for scripting.

  ## Availability
  The CLI can be used across [all regions](https://www.linode.com/global-infrastructure/).

  ## Pricing
  The CLI is provided free of charge to all customers.

  ## Usage
  Invoke with `linode-cli`, `linode`, or simply `lin`.
base: core24
grade: stable
confinement: strict
source-code:
  - https://github.com/linode/linode-cli
  - https://github.com/adamovera/linode-cli-snap
contact:
  - https://www.linode.com/support/
  - https://adamovera.com/contact
website:
  - https://techdocs.akamai.com/cloud-computing/docs/cli
  - https://github.com/linode/linode-cli
issues:
  - https://github.com/linode/linode-cli/issues
  - https://github.com/adamovera/linode-cli-snap/issues
icon: icon.png

platforms:
  amd64:
    build-on:
      - amd64
    build-for:
      - amd64
  arm64:
    build-on:
      - amd64
      - arm64
    build-for:
      - arm64

apps:
  linode-cli:
    command: bin/linode-cli
    aliases:
      - linode
      - lin
    plugs:
      - home
      - network

parts:
  linode-cli:
    plugin: python
    source: .
    python-packages:
      - linode-cli==$SNAPCRAFT_PROJECT_VERSION
